version: '2.1'

services:
  web:
    build: .
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - "8080:8080"
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=familybudget
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"